set(SURVIVAL_ISLAND_CLIENT_VERSION_MAJOR    1)
set(SURVIVAL_ISLAND_CLIENT_VERSION_MINOR    3)
set(SURVIVAL_ISLAND_CLIENT_VERSION_REVISION 0)

set(SURVIVAL_ISLAND_CLIENT_VERSION "${SURVIVAL_ISLAND_CLIENT_VERSION_MAJOR}.${SURVIVAL_ISLAND_CLIENT_VERSION_MINOR}.${SURVIVAL_ISLAND_CLIENT_VERSION_REVISION}")

set(SURVIVAL_ISLAND_SERVER_VERSION_MAJOR    2)
set(SURVIVAL_ISLAND_SERVER_VERSION_MINOR    0)
set(SURVIVAL_ISLAND_SERVER_VERSION_REVISION 4)

set(SURVIVAL_ISLAND_SERVER_VERSION "${SURVIVAL_ISLAND_SERVER_VERSION_MAJOR}.${SURVIVAL_ISLAND_SERVER_VERSION_MINOR}.${SURVIVAL_ISLAND_SERVER_VERSION_REVISION}")
