set(SURVIVAL_ISLAND_VERSION_MAJOR 1)
set(SURVIVAL_ISLAND_VERSION_MINOR 0)
set(SURVIVAL_ISLAND_VERSION_PATCH 1)

set(SURVIVAL_ISLAND_VERSION "${SURVIVAL_ISLAND_VERSION_MAJOR}.${SURVIVAL_ISLAND_VERSION_MINOR}.${SURVIVAL_ISLAND_VERSION_PATCH}")
